version: '3'
services:
  app:
    container_name: 'app'
    ports:
      - '8000:80'
    build:
      context: .
      dockerfile: './Dockerfile'
    networks:
      - mvp
    volumes:
      - '.:/app'
      - 'reports:/app/reports'
    env_file:
      - '.env'
    
  db:
    image: 'postgres:14-alpine'
    container_name: 'db'
    ports:
      - '5300:5432'
    environment:
      PGPASSWORD: 'app'
      POSTGRES_DB: 'app'
      POSTGRES_USER: 'app'
      POSTGRES_PASSWORD: 'app'
    networks:
      - mvp
    volumes:
      - 'db:/var/lib/postgresql/data'
      - ./init-scripts:/docker-entrypoint-initdb.d

networks:
  mvp:
volumes:
  db:
  reports:
